# Configuration file for oakd-camera-tracking pipeline. Adjust settings as needed for your environment and use case.
dev_or_pi : "dev" # Set to "dev" for development environment, "pi" for Raspberry Pi deployment
live_view_enabled : True # Whether to display the camera feed(s) in real-time. Boolean value.
recording_enabled : True # Whether to record the camera feed(s) to disk. Boolean value.
inference_enabled : False # Whether to run boat detection on the camera feed(s). Boolean value.
record_gyroscope : True # Whether to record gyroscope data to disk. Boolean value.
camera_feed_output_dir : "output/recordings/" # Directory to save recorded camera feeds (if recording enabled). Default is "output/recordings/".
